version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/basic_inventory_control?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: basic_inventory_control
    ports:
      - "3006:3306"
