services:
  frontend:
    build:
      context: basic-inventory-dashboard/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=http://api:8080
    depends_on:
      - api
      - db
    networks:
      - basic_inventory_network

  api:
    build:
      context: basic-inventory-api/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3002:8080"
    environment:
      - SPRING_DB_USERNAME=basic_inventory_api
      - SPRING_DB_PASSWORD=api123
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/basic_inventory?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DLL=none
      - SPRING_HIKARI_MAX_POOL_SIZE=20
      - SPRING_HIKARI_MIN_POOL_SIZE=3
      - SPRING_HIKARI_IDLE_TIMEOUT_MSECS=15000
      - SPRING_HIKARI_CONNECTION_TIMEOUT_MSECS=30000
      - SPRING_HIKARI_CONNECTION_MAX_LIFETIME_MSECS=60000
      - SWAGGER_API_DOCS=/v3/api-docs
      - SWAGGER_UI_PATH=/swagger-ui.html
      - SWAGGER_UI_CONFIG=/v3/api-docs/swagger-config
      - SWAGGER_SHOW_REQUEST_DURATION=true
    depends_on:
      - db
    networks:
      - basic_inventory_network

  db:
    build:
      context: basic-inventory-db/
      dockerfile: Dockerfile
    environment:
      - MARIADB_DATABASE=basic_inventory
      - MARIADB_ROOT_PASSWORD=admin123
      - MARIADB_USER=basic_inventory_api
      - MARIADB_PASSWORD=api123
    ports:
      - "3001:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - basic_inventory_network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: C:\db
      # device: /home/jvlerner/db
      o: bind

networks:
  basic_inventory_network:
    driver: bridge
