version: '3.8'

services:
#   view:
#     build:
#       context: basic-inventory-view/
#       dockerfile: Dockerfile
#     restart: on-failure
#     ports:
#       - "3003:3000"
#     environment:
#       - API_URL=null
#     depends_on:
#       - api
#       - db

  api:
    build:
      context: basic-inventory-api/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3002:8080"
    environment:
      - SPRING_DB_USERNAME=basic_inventory_api
      - SPRING_DB_PASSWORD=api123
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/basic_inventory?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DLL=none
      - SPRING_HIKARI_MAX_POOL_SIZE=20
      - SPRING_HIKARI_MIN_POOL_SIZE=3
      - SPRING_HIKARI_IDLE_TIMEOUT_MSECS=15000
      - SPRING_HIKARI_CONNECTION_TIMEOUT_MSECS=30000
      - SPRING_HIKARI_CONNECTION_MAX_LIFETIME_MSECS=60000
      - SWAGGER_API_DOCS=/v3/api-docs
      - SWAGGER_UI_PATH=/swagger-ui.html
      - SWAGGER_UI_CONFIG=/v3/api-docs/swagger-config
      - SWAGGER_SHOW_REQUEST_DURATION=true
    depends_on:
      - db

  db:
    build:
      context: basic-inventory-db/
      dockerfile: Dockerfile
    environment:
      - MARIADB_DATABASE=basic_inventory
      - MARIADB_ROOT_PASSWORD=admin123
      - MARIADB_USER=basic_inventory_api
      - MARIADB_PASSWORD=api123
    ports:
      - "3001:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: C:\db
      o: bind

